
source 'https://github.com/hydreamit/Specs.git'
source 'https://cdn.cocoapods.org/'

use_frameworks!
platform :ios, '9.0'

target 'HyBaseComponents_Example' do
  pod 'HyBaseComponents', :path => '../'

  target 'HyBaseComponents_Tests' do
    inherit! :search_paths

    
  end
end


#s.subspec 'Categories' do |ss|
#    ss.source_files = 'HyBaseComponents/Classes/Categories/**/*'
#    ss.dependency 'ReactiveObjC'
#end
#
#s.subspec 'TipView' do |ss|
#    ss.source_files = 'HyBaseComponents/Classes/TipView/**/*'
#end
#
#s.subspec 'Network' do |ss|
#    ss.source_files = 'HyBaseComponents/Classes/Network/**/*'
#    ss.dependency 'AFNetworking'
#    ss.dependency 'YYCache'
#    ss.dependency 'HyBaseComponents/TipView'
#end
#
#s.subspec 'ModelParser' do |ss|
#    ss.source_files = 'HyBaseComponents/Classes/ModelParser/**/*'
#    ss.dependency 'YYModel'
#    ss.dependency 'MJExtension'
#end
#
#s.subspec 'RefreshView' do |ss|
#    ss.source_files = 'HyBaseComponents/Classes/RefreshView/**/*'
#    ss.dependency 'MJRefresh'
#    ss.dependency 'KafkaRefresh'
#end
#
#s.subspec 'MVVM' do |ss|
#    ss.source_files = 'HyBaseComponents/Classes/MVVM/**/*'
#    ss.dependency 'HyBaseComponents/Network'
#    ss.dependency 'HyBaseComponents/ModelParser'
#    ss.dependency 'HyBaseComponents/Categories'
#end
#
#s.subspec 'Monitor' do |ss|
#    ss.source_files = 'HyBaseComponents/Classes/Monitor/**/*'
#end
