

use_frameworks!
platform :ios, '9.0'

target 'HyBaseComponents_Example' do
  pod 'HyBaseComponents', :path => '../'

  target 'HyBaseComponents_Tests' do
    inherit! :search_paths

    
  end
end

